### ISSUE TITLE
it is not pulling from source, it only pulls from the forked user's repo

### ISSUE THREAD

**Issue by shaunstanislaus** [IonicaBizau/pull-from-source#3]
# Example 
## repo -  johnsmith/foobar

i fork `git@github.com:johnsmith/foobar.git`

i clone `git@github.com:shaunstanislaus/foobar.git`

i go into the repository and do `pull-from-source` , it only pulls from the remote that existing in the remote like myself, the original source does not exist such as johnsmith.

is there anyway or if github provides an API to check a forked's original sourced and you can probably write in the function, i think that is the missing part of this library.

<img width="370" alt="screen shot 2016-08-08 at 10 56 47" src="https://cloud.githubusercontent.com/assets/1703530/17468079/f5090c68-5d56-11e6-8eac-fc22017afebe.png">

see above picture, it says " forked from ..... " after i fork it, on github website it knows its original source that i forked from."

once you solve the function to GET the original source repo from the clone repo , it will nicely accompany `gh-fork-source`

hope you can help to solve this and update me on this again?

**Comment by IonicaBizau** [comment]
Hmm, looks like a bug. I will test it. It is supposed to use the GitHub API already.

**Comment by shaunstanislaus** [comment]
okay, let me know once you fixed it (: , looking forward to it. @IonicaBizau

**Comment by shaunstanislaus** [comment]
any updates yet? @IonicaBizau

**Comment by IonicaBizau** [comment]
@shaunstanislaus Sorry, not yet, but if I don't solve this this week, just ping me again. 😁

**Comment by shaunstanislaus** [comment]
okay (: @IonicaBizau

**Comment by shaunstanislaus** [comment]
hi @ionicaBizau , pinging you here! (: heres a reminder.

**Comment by IonicaBizau** [comment]
I'm on it, thanks!

**Comment by shaunstanislaus** [comment]
hi @IonicaBizau , its not solved.

it is still pulling from its own forked repo instead of the original user's source code that you fork from.

please kindly rectify.

**Comment by IonicaBizau** [comment]
Hmm, I cannot reproduce it anymore. Did you reinstall the latest version?

**Comment by shaunstanislaus** [comment]
hi @ionicaBizau ,i just merely pull your new commits, you are suggesting a reinstall meaning re clone it ?

**Comment by IonicaBizau** [comment]
`npm i -g pull-from-source` and then `cd` into your cloned fork and run `pull-from-source`

**Comment by shaunstanislaus** [comment]
hi @ionicaBizau it works! this is a life saver, thank you!
